import type { ExperienceEntry, Skills } from '@/types/about.types'
import type { Translator } from '@/types/i18n.types'

export const clients = 3
export const completedProjects = 20
export const yearsOfExperience = 2

export const experienceData = (t: Translator): ExperienceEntry[] => [
  {
    position: t('about.experience.cgs-team.position'),
    company: 'CGS-team',
    companyLink: 'https://cgsteam.io/',
    time: '2024-Present',
    address: t('about.experience.cgs-team.address'),
    description: t('about.experience.cgs-team.description'),
    responsibilities: [
      t('about.experience.cgs-team.responsibilities.0'),
      t('about.experience.cgs-team.responsibilities.1'),
      t('about.experience.cgs-team.responsibilities.2'),
      t('about.experience.cgs-team.responsibilities.3'),
      t('about.experience.cgs-team.responsibilities.4'),
      t('about.experience.cgs-team.responsibilities.5'),
      t('about.experience.cgs-team.responsibilities.6'),
    ],
  },
  {
    position: t('about.experience.goit.position'),
    company: 'GoIT',
    companyLink: 'https://goit.global/ua/',
    time: '2023 - 2024',
    address: t('about.experience.goit.address'),
    description: t('about.experience.goit.description'),
    responsibilities: [
      t('about.experience.goit.responsibilities.0'),
      t('about.experience.goit.responsibilities.1'),
      t('about.experience.goit.responsibilities.2'),
      t('about.experience.goit.responsibilities.3'),
    ],
  },
  {
    position: t('about.experience.softserve.position'),
    company: 'SoftServe',
    companyLink: 'https://www.softserveinc.com/en-us',
    time: '2022 - 2023',
    address: t('about.experience.softserve.address'),
    description: t('about.experience.softserve.description'),
    responsibilities: [
      t('about.experience.softserve.responsibilities.0'),
      t('about.experience.softserve.responsibilities.1'),
      t('about.experience.softserve.responsibilities.2'),
      t('about.experience.softserve.responsibilities.3'),
      t('about.experience.softserve.responsibilities.4'),
      t('about.experience.softserve.responsibilities.5'),
    ],
  },
]

export const skills: Skills = {
  frontend: [
    'JavaScript',
    'React',
    'Redux',
    'Redux Toolkit',
    'Next.js',
    'HTML',
    'CSS',
    'Sass',
    'SCSS',
    'Tailwind CSS',
    'MaterialUI',
    'Bootstrap',
    'Framer Motion',
    'DOM',
    'JQuery',
  ],
  backend: [
    'Node.js',
    'Express',
    'Nest.js',
    'REST API',
    'GraphQL',
    'WebSocket',
    'Validation',
    'JWT/OAuth',
    'SQL',
    'Postgres',
    'TypeOrm',
    'MongoDB',
    'Mongoose',
    'Stripe',
    'SSR',
    'Postman',
  ],
  other: [
    'TypeScript',
    'Git',
    'GitHub',
    'Npm',
    'Yarn',
    'Vercel',
    'Figma',
    'StoryBook',
    'Docker',
    'Firebase',
    'DynamoDB',
    'AWS Lightsail',
    'AWS Amplify',
    'AWS S3',
    'AWS Lambda',
    'Jest',
    'Enzyme',
    'RTL',
    'Scrum',
    'CI/CD',
    'Blockchain',
    'Solidity',
    'Ethereum',
    'Smart Contracts',
    'Hardhat',
    'ESLint',
    'Prettier',
  ],
}
